#!/usr/bin/env python3

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = ROOT / "project-status.json"
README_PATH = ROOT / "README.md"
PROJECT_META_PATH = ROOT / "docs" / "assets" / "project-meta.js"
WIKI_PATHS = [
    ROOT / "wiki" / "Home.md",
    ROOT / "wiki" / "Development-Status.md",
    ROOT / "wiki" / "Versioning-and-Releases.md",
]
def load_status():
    status = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
    required = {
        "schema_version",
        "version",
        "stage",
        "milestone",
        "minecraft_version",
        "forge_version",
        "java_version",
        "last_updated",
        "last_updated_utc",
    }
    missing = sorted(required - status.keys())
    if missing:
        raise ValueError(f"project-status.json 缺少字段: {', '.join(missing)}")
    if status["schema_version"] != 1:
        raise ValueError("不支持的 project-status.json schema_version")
    version_pattern = re.compile(
        rf"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?-{re.escape(status['minecraft_version'])}$"
    )
    if not version_pattern.fullmatch(status["version"]):
        raise ValueError("version 必须使用 <SemVer>-<Minecraft 版本> 格式")
    local_time = datetime.fromisoformat(status["last_updated"])
    utc_time = datetime.fromisoformat(status["last_updated_utc"].replace("Z", "+00:00"))
    if local_time.tzinfo is None or utc_time.tzinfo is None:
        raise ValueError("更新时间必须包含时区")
    if local_time.astimezone(utc_time.tzinfo) != utc_time:
        raise ValueError("last_updated 与 last_updated_utc 不一致")
    gradle_properties = {}
    for line in (ROOT / "gradle.properties").read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            gradle_properties[key.strip()] = value.strip()
    expected_properties = {
        "minecraft_version": status["minecraft_version"],
        "forge_version": status["forge_version"],
    }
    for key, expected in expected_properties.items():
        if gradle_properties.get(key) != expected:
            raise ValueError(
                f"{key} 与 gradle.properties 不一致: "
                f"{expected!r} != {gradle_properties.get(key)!r}"
            )
    return status, local_time


def status_block(status, local_time, prefix="> "):
    offset = local_time.strftime("%z")
    offset_text = f"UTC{offset[:3]}:{offset[3:]}"
    lines = [
        f"当前版本：**`{status['version']}`**",
        f"开发阶段：**{status['stage']}**（{status['milestone']}）",
        (
            f"技术基线：Minecraft **{status['minecraft_version']}** · "
            f"Forge **{status['forge_version']}** · Java **{status['java_version']}**"
        ),
        (
            f"最后更新：**{local_time.strftime('%Y-%m-%d %H:%M:%S')} "
            f"{offset_text}**（`{status['last_updated_utc']}`）"
        ),
    ]
    return "\n".join(prefix + line for line in lines)


def replace_block(text, name, content):
    start = f"<!-- {name}:start -->"
    end = f"<!-- {name}:end -->"
    pattern = re.compile(
        rf"{re.escape(start)}.*?{re.escape(end)}",
        flags=re.DOTALL,
    )
    replacement = f"{start}\n{content}\n{end}"
    updated, count = pattern.subn(replacement, text)
    if count != 1:
        raise ValueError(f"{name} 标记块数量应为 1，实际为 {count}")
    return updated


def render_project_meta(status, local_time):
    offset = local_time.strftime("%z")
    display = (
        f"{local_time.strftime('%Y-%m-%d %H:%M:%S')} "
        f"UTC{offset[:3]}:{offset[3:]}"
    )
    payload = {
        "version": status["version"],
        "stage": status["stage"],
        "milestone": status["milestone"],
        "mc": f"Minecraft Java {status['minecraft_version']}",
        "loader": f"Forge {status['forge_version']}",
        "java": status["java_version"],
        "lastUpdated": status["last_updated"],
        "lastUpdatedUtc": status["last_updated_utc"],
        "lastUpdatedDisplay": display,
    }
    encoded = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "/* Generated by scripts/sync_project_metadata.py. */\n"
        f"window.LOM_PROJECT_META = {encoded};\n"
    )


def expected_files(status, local_time):
    expected = {}
    readme = README_PATH.read_text(encoding="utf-8")
    expected[README_PATH] = replace_block(
        readme,
        "project-status",
        status_block(status, local_time, prefix="> - "),
    )
    wiki_block = status_block(status, local_time, prefix="- ")
    for path in WIKI_PATHS:
        text = path.read_text(encoding="utf-8")
        expected[path] = replace_block(text, "project-status", wiki_block)
    expected[PROJECT_META_PATH] = render_project_meta(status, local_time)
    return expected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="只检查生成内容是否同步，不写入文件",
    )
    args = parser.parse_args()

    try:
        status, local_time = load_status()
        expected = expected_files(status, local_time)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"metadata sync error: {error}", file=sys.stderr)
        return 1

    stale = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

    if args.check and stale:
        print("以下文件与 project-status.json 不同步：", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        print("请运行: python scripts/sync_project_metadata.py", file=sys.stderr)
        return 1

    action = "checked" if args.check else "updated"
    print(f"project metadata {action}: {len(expected)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
